#!/usr/bin/env bash


 #
 # Author: Andrew Peters
 #
 # Copyright 2019 United States Government as represented by the Administrator of the National Aeronautics
 # and Space Administration. All Rights Reserved.
 #  
 # Disclaimers
 # No Warranty: THE SUBJECT SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY WARRANTY OF ANY
 # KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY
 # WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO SPECIFICATIONS, ANY IMPLIED
 # WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR FREEDOM FROM
 # INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE ERROR FREE, OR ANY
 # WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM TO THE SUBJECT SOFTWARE.
 # THIS AGREEMENT DOES NOT, IN ANY MANNER, CONSTITUTE AN ENDORSEMENT BY GOVERNMENT
 # AGENCY OR ANY PRIOR RECIPIENT OF ANY RESULTS, RESULTING DESIGNS, HARDWARE,
 # SOFTWARE PRODUCTS OR ANY OTHER APPLICATIONS RESULTING FROM USE OF THE SUBJECT
 # SOFTWARE.  FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES AND LIABILITIES
 # REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE, AND
 # DISTRIBUTES IT "AS IS."
 #  
 # Waiver and Indemnity:  RECIPIENT AGREES TO WAIVE ANY AND ALL CLAIMS AGAINST THE UNITED
 # STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY PRIOR
 # RECIPIENT.  IF RECIPIENT'S USE OF THE SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES,
 # DEMANDS, DAMAGES, EXPENSES OR LOSSES ARISING FROM SUCH USE, INCLUDING ANY
 # DAMAGES FROM PRODUCTS BASED ON, OR RESULTING FROM, RECIPIENT'S USE OF THE SUBJECT
 # SOFTWARE, RECIPIENT SHALL INDEMNIFY AND HOLD HARMLESS THE UNITED STATES
 # GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT,
 # TO THE EXTENT PERMITTED BY LAW.  RECIPIENT'S SOLE REMEDY FOR ANY SUCH MATTER SHALL
 # BE THE IMMEDIATE, UNILATERAL TERMINATION OF THIS AGREEMENT.
 #


while getopts v:l:s:i:m:p: option
do
case "${option}"
in
v) TYPE=${OPTARG};;
l) LATLNG=${OPTARG};;
s) SPEED=${OPTARG};;
i) INSTANCE=${OPTARG};;
m) MASTER=${OPTARG};;
p) P=${OPTARG}
esac
done
HERE=$PWD
# change path to ardupilot
cd $HOME$P/Tools/autotest
echo $PWD
# cd $HOME/Documents/Software/ardupilot/Tools/autotest

python sim_vehicle.py -v $TYPE -l $LATLNG -S $SPEED -I $INSTANCE -w >| $HERE/LogFiles/ardusimout$INSTANCE.txt
# sim_vehicle.py -v ArduCopter -l 37.0866,-76.3789,5.000000,0 -S 1 -I 0 -m "--out=127.0.0.1:14553"
